name: Rafeeq
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.1+1
  path_provider: ^2.1.5
  path: ^1.8.3
  dio: ^5.9.1
  flutter_bloc: ^9.1.1
  google_fonts: ^8.0.2
  url_launcher: ^6.3.2
  country_picker: ^2.0.27
  flutter_secure_storage: ^10.0.0
  flutter_localizations:
    sdk: flutter   
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^2.0.1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.5
  flutter_animate: ^4.5.2
  animated_text_kit: ^4.3.0
  image_picker: ^1.2.1
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  flutter_tts: ^4.2.5
  audio_waveforms: ^2.0.2
  image_cropper: ^12.2.1
  shimmer: ^3.0.0
  google_sign_in: ^6.2.1
  calendar_date_picker2: ^2.0.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# إعدادات الأيقونة
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/iconapp.jpeg"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/iconapp.jpeg"

flutter:
  uses-material-design: true
  generate: true   # مهم جدًا لتوليد AppLocalizations

  assets:
    - assets/images/